### PR TITLE
DOCSTRINGS to functions

### LINKED ISSUE #20: Add docstrings to functions
Overall:
A docstring should be included at the top of code  to summarize project @adiChat This might be good for you to do

Specifically (see example below):  This could be done by other contributers
  1. Docstrings should be added to each function.
  2. The docstrings in each function must include argument type with short description
  3. The docstrings in each function must include a return type

```python
    def is_cow(sound):
        ''' Checks if cow makes inputted sound 
        Args:
            sound(str): sound the animal makes
        Returns:
            bool: True for success, False otherwise.
        '''
        if sound == 'moo':
            return True
        else:
            return False
```

### PR DESCRIPTION
**Pull request by bhaveshAn**
@AdiChat 
Fixes #20 Kindly merge this PR.

### CODE REVIEW

**Comment by bhaveshAn** [comment]
@AdiChat please review ! Thanks

**Comment by AdiChat** [comment]
Kindly resolve the conflict 👍 

It will be good to merge then 👍

**Comment by lwgray** [comment]
In a couple of the docstrings... the Return type is not described.

**Comment by bhaveshAn** [comment]
@AdiChat please merge this PR. Resolved conflicts. Thanks !
@lwgray doctrings for all return type functions has been done. Kindly review. Thanks !

**Comment by lwgray** [comment]
@bhaveshAn I missed it before but in addition to the Return description, the object type should be included

**Comment by bhaveshAn** [comment]
@lwgray Is it fine now ?

**Comment by lwgray** [comment]
looks good

**Comment by AdiChat** [comment]
Looks good 👍 

Hope you are enjoying your journey with **OpenGenus**

**Pull request merged**
