### PR TITLE
Updated CONTRIBUTORS.md/CONTRIBUTING.md files

### PR DESCRIPTION
**Pull request by JamesMCo**
- Updated to include new contributors
- Also fixed broken link to COMMIT_TEMPLATE.md file

### CODE REVIEW

**Comment by JayTurnr** [comment]
Seems when my pull request got merged it duplicated CONTRIBERS.md/CONTRIBUTING.md

I think it's time to merge these two again... The real question is... why was it moved to .github/

**Comment by AdiChat** [comment]
@bhaveshAn What is the purpose to move the files to `.github` folder?

**Comment by bhaveshAn** [comment]
> The real question is... why was it moved to .github/

It is done because when the PR is merged containing the template. For subsequent issues, and PR it looks in the `.github` dir and same template is available for every new issue and PR.

for templates like ISSUE_TEMPALTE.md and CONTRIBUTING.md , both should be in `.github/`

**Comment by JayTurnr** [comment]
Ah! Also read somewhere after commenting that the wiki is simply .md files in .github :P

**Comment by AdiChat** [comment]
Looks good 👍 

Hope you are enjoying your journey with **OpenGenus**

**Comment by JamesMCo** [comment]
I've just realised that I accidentally provided the incorrect url for [Bhavesh Anand](https://github.com/bhaveshAn) (I used [Vipul's](https://github.com/vipul-sharma20) profile instead). Will submit a fix :+1:

**Comment by bhaveshAn** [comment]
@JamesMCo please do. Thanks !

**Comment by lwgray** [comment]
I think it is common practice to include commit/issue template in .github or docs folder.  [see github doc](https://help.github.com/articles/creating-an-issue-template-for-your-repository/)

**Comment by bhaveshAn** [comment]
Yeah

**Pull request merged**
