### PR TITLE
CONTRIBUTING.md

### LINKED ISSUE #14: CONTRIBUTING.md - Instructions on how to contribute to Vidsum
:memo:
To help contributors get more easily started, I think there should be a contributing.md file.  It would be a general guide on how to contribute to Vidsum.  

This file could contain information on:
1. Code of Conduct
2. Style guide (ie PEP8)
3. Info on committing & pull requests

Here is an example template of a [CONTRIBUTING.md ](https://github.com/thoughtbot/templates/blob/master/CONTRIBUTING.md.template) file

Implementing this  would address issue #13

### PR DESCRIPTION
**Pull request by bhaveshAn**
@AdiChat 
Changing `contributors.md` -->  `.github/CONTRIBUTING.md`
                `ISSUE_TEMPLATE.md`  -->  `.github/ISSUE_TEMPLATE.md`

Fixes #14 
Kindly merge this PR, Thanks !

### CODE REVIEW

**Comment by bhaveshAn** [comment]
@AdiChat please review !

**Comment by AdiChat** [comment]
Looks good 👍 

Hope you are enjoying your journey with **OpenGenus**

**Comment by JayTurnr** [comment]
This duplicated `CONTRIBTORS.md` as that was renamed from `contributors.md` in PR #28

**Comment by bhaveshAn** [comment]
The #14  issue is concerning `CONTRIBUTING.md` and not `contributors.md` or `CONTRIBUTORS.md`

**Pull request merged**
